# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Doc_add_window.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DocWindow(object):
    def setupUi(self, DocWindow):
        DocWindow.setObjectName("DocWindow")
        DocWindow.resize(708, 355)
        self.centralwidget = QtWidgets.QWidget(DocWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.NameEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.NameEdit.setGeometry(QtCore.QRect(60, 70, 261, 20))
        self.NameEdit.setObjectName("NameEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 50, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 100, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.SpecEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.SpecEdit.setGeometry(QtCore.QRect(60, 120, 261, 20))
        self.SpecEdit.setObjectName("SpecEdit")
        self.CabEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.CabEdit.setGeometry(QtCore.QRect(60, 170, 61, 20))
        self.CabEdit.setObjectName("CabEdit")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 150, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.buttonBox.setGeometry(QtCore.QRect(520, 280, 156, 23))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.groupbox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupbox.setGeometry(QtCore.QRect(400, 50, 241, 145))
        self.groupbox.setObjectName("groupbox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupbox)
        self.gridLayout.setObjectName("gridLayout")
        self.timeEdit_2 = QtWidgets.QLineEdit(self.groupbox)
        self.timeEdit_2.setEnabled(False)
        self.timeEdit_2.setObjectName("timeEdit_2")
        self.gridLayout.addWidget(self.timeEdit_2, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupbox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupbox)
        self.checkBox_4.setChecked(False)
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout.addWidget(self.checkBox_4, 6, 0, 1, 1)
        self.timeEdit_1 = QtWidgets.QLineEdit(self.groupbox)
        self.timeEdit_1.setEnabled(False)
        self.timeEdit_1.setObjectName("timeEdit_1")
        self.gridLayout.addWidget(self.timeEdit_1, 2, 1, 1, 1)
        self.checkBox_5 = QtWidgets.QCheckBox(self.groupbox)
        self.checkBox_5.setChecked(False)
        self.checkBox_5.setObjectName("checkBox_5")
        self.gridLayout.addWidget(self.checkBox_5, 7, 0, 1, 1)
        self.timeEdit_4 = QtWidgets.QLineEdit(self.groupbox)
        self.timeEdit_4.setEnabled(False)
        self.timeEdit_4.setObjectName("timeEdit_4")
        self.gridLayout.addWidget(self.timeEdit_4, 6, 1, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupbox)
        self.checkBox_2.setChecked(False)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout.addWidget(self.checkBox_2, 3, 0, 1, 1)
        self.checkBox_1 = QtWidgets.QCheckBox(self.groupbox)
        self.checkBox_1.setChecked(False)
        self.checkBox_1.setObjectName("checkBox_1")
        self.gridLayout.addWidget(self.checkBox_1, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupbox)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 1, 1, 1)
        self.timeEdit_5 = QtWidgets.QLineEdit(self.groupbox)
        self.timeEdit_5.setEnabled(False)
        self.timeEdit_5.setObjectName("timeEdit_5")
        self.gridLayout.addWidget(self.timeEdit_5, 7, 1, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupbox)
        self.checkBox_3.setChecked(False)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout.addWidget(self.checkBox_3, 4, 0, 1, 1)
        self.timeEdit_3 = QtWidgets.QLineEdit(self.groupbox)
        self.timeEdit_3.setEnabled(False)
        self.timeEdit_3.setObjectName("timeEdit_3")
        self.gridLayout.addWidget(self.timeEdit_3, 4, 1, 1, 1)
        DocWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(DocWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 708, 21))
        self.menubar.setObjectName("menubar")
        DocWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(DocWindow)
        self.statusbar.setObjectName("statusbar")
        DocWindow.setStatusBar(self.statusbar)

        self.retranslateUi(DocWindow)
        self.checkBox_1.toggled['bool'].connect(self.timeEdit_1.setEnabled)
        self.checkBox_2.toggled['bool'].connect(self.timeEdit_2.setEnabled)
        self.checkBox_3.toggled['bool'].connect(self.timeEdit_3.setEnabled)
        self.checkBox_4.toggled['bool'].connect(self.timeEdit_4.setEnabled)
        self.checkBox_5.toggled['bool'].connect(self.timeEdit_5.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(DocWindow)

    def retranslateUi(self, DocWindow):
        _translate = QtCore.QCoreApplication.translate
        DocWindow.setWindowTitle(_translate("DocWindow", "MainWindow"))
        self.NameEdit.setText(_translate("DocWindow", "Иван Иванович"))
        self.label.setText(_translate("DocWindow", "ФИО"))
        self.label_2.setText(_translate("DocWindow", "Специализация"))
        self.SpecEdit.setText(_translate("DocWindow", "Кардиолог"))
        self.CabEdit.setText(_translate("DocWindow", "147"))
        self.label_3.setText(_translate("DocWindow", "Кабинет"))
        self.timeEdit_2.setText(_translate("DocWindow", "9.00 - 16.00"))
        self.label_4.setText(_translate("DocWindow", "День недели"))
        self.checkBox_4.setText(_translate("DocWindow", "ЧТ"))
        self.timeEdit_1.setText(_translate("DocWindow", "9.00 - 16.00"))
        self.checkBox_5.setText(_translate("DocWindow", "ПТ"))
        self.timeEdit_4.setText(_translate("DocWindow", "9.00 - 16.00"))
        self.checkBox_2.setText(_translate("DocWindow", "ВТ"))
        self.checkBox_1.setText(_translate("DocWindow", "ПН"))
        self.label_5.setText(_translate("DocWindow", "Время"))
        self.timeEdit_5.setText(_translate("DocWindow", "9.00 - 16.00"))
        self.checkBox_3.setText(_translate("DocWindow", "СР"))
        self.timeEdit_3.setText(_translate("DocWindow", "9.00 - 16.00"))

