# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\doc_add_window_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(666, 333)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setEnabled(True)
        self.groupBox.setGeometry(QtCore.QRect(400, 50, 241, 145))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.timeEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.timeEdit_2.setEnabled(False)
        self.timeEdit_2.setObjectName("timeEdit_2")
        self.gridLayout.addWidget(self.timeEdit_2, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_4.setChecked(False)
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout.addWidget(self.checkBox_4, 6, 0, 1, 1)
        self.timeEdit_1 = QtWidgets.QLineEdit(self.groupBox)
        self.timeEdit_1.setEnabled(False)
        self.timeEdit_1.setObjectName("timeEdit_1")
        self.gridLayout.addWidget(self.timeEdit_1, 2, 1, 1, 1)
        self.checkBox_5 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_5.setChecked(False)
        self.checkBox_5.setObjectName("checkBox_5")
        self.gridLayout.addWidget(self.checkBox_5, 7, 0, 1, 1)
        self.timeEdit_4 = QtWidgets.QLineEdit(self.groupBox)
        self.timeEdit_4.setEnabled(False)
        self.timeEdit_4.setObjectName("timeEdit_4")
        self.gridLayout.addWidget(self.timeEdit_4, 6, 1, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_2.setChecked(False)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout.addWidget(self.checkBox_2, 3, 0, 1, 1)
        self.checkBox_1 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_1.setChecked(False)
        self.checkBox_1.setObjectName("checkBox_1")
        self.gridLayout.addWidget(self.checkBox_1, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 1, 1, 1)
        self.timeEdit_5 = QtWidgets.QLineEdit(self.groupBox)
        self.timeEdit_5.setEnabled(False)
        self.timeEdit_5.setObjectName("timeEdit_5")
        self.gridLayout.addWidget(self.timeEdit_5, 7, 1, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_3.setChecked(False)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout.addWidget(self.checkBox_3, 4, 0, 1, 1)
        self.timeEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.timeEdit_3.setEnabled(False)
        self.timeEdit_3.setObjectName("timeEdit_3")
        self.gridLayout.addWidget(self.timeEdit_3, 4, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(60, 150, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(60, 100, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.NameEdit = QtWidgets.QLineEdit(Dialog)
        self.NameEdit.setGeometry(QtCore.QRect(60, 70, 261, 20))
        self.NameEdit.setObjectName("NameEdit")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(480, 280, 156, 23))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.CabEdit = QtWidgets.QLineEdit(Dialog)
        self.CabEdit.setGeometry(QtCore.QRect(60, 170, 61, 20))
        self.CabEdit.setObjectName("CabEdit")
        self.SpecEdit = QtWidgets.QLineEdit(Dialog)
        self.SpecEdit.setGeometry(QtCore.QRect(60, 120, 261, 20))
        self.SpecEdit.setObjectName("SpecEdit")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(60, 50, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        self.checkBox_1.toggled['bool'].connect(self.timeEdit_1.setEnabled)
        self.checkBox_2.toggled['bool'].connect(self.timeEdit_2.setEnabled)
        self.checkBox_3.toggled['bool'].connect(self.timeEdit_3.setEnabled)
        self.checkBox_4.toggled['bool'].connect(self.timeEdit_4.setEnabled)
        self.checkBox_5.toggled['bool'].connect(self.timeEdit_5.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.timeEdit_2.setText(_translate("Dialog", "9.00 - 16.00"))
        self.label_4.setText(_translate("Dialog", "День недели"))
        self.checkBox_4.setText(_translate("Dialog", "ЧТ"))
        self.timeEdit_1.setText(_translate("Dialog", "9.00 - 16.00"))
        self.checkBox_5.setText(_translate("Dialog", "ПТ"))
        self.timeEdit_4.setText(_translate("Dialog", "9.00 - 16.00"))
        self.checkBox_2.setText(_translate("Dialog", "ВТ"))
        self.checkBox_1.setText(_translate("Dialog", "ПН"))
        self.label_5.setText(_translate("Dialog", "Время"))
        self.timeEdit_5.setText(_translate("Dialog", "9.00 - 16.00"))
        self.checkBox_3.setText(_translate("Dialog", "СР"))
        self.timeEdit_3.setText(_translate("Dialog", "9.00 - 16.00"))
        self.label_3.setText(_translate("Dialog", "Кабинет"))
        self.label_2.setText(_translate("Dialog", "Специализация"))
        self.NameEdit.setText(_translate("Dialog", "Иван Иванович"))
        self.CabEdit.setText(_translate("Dialog", "147"))
        self.SpecEdit.setText(_translate("Dialog", "Кардиолог"))
        self.label.setText(_translate("Dialog", "ФИО"))

